version: '3.1'
services:
  #app:
  #  container_name: app-players
  #  image: app-players
  #  build: ./
  #  ports:
  #    - "8080:8080"
  #  depends_on:
  #    - zookeeper
  #    - kafka
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "novice-players:1:3"